const menuButton=document.getElementById('menu-button');
const navLinks=document.getElementById('nav-links');
menuButton.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open));});
navLinks.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{navLinks.classList.remove('open');menuButton.setAttribute('aria-expanded','false');}));
document.getElementById('year').textContent=`© ${new Date().getFullYear()} ORVIAN`;
// Content is local and editable. No user accounts, tracking, or external dependencies.
const projects={
server:{label:'PROJECT / INFRASTRUCTURE',title:'Prime Server',body:`<p><strong>Why I built it:</strong> I wanted to understand how a personal server could manage files and services across my own devices.</p><h3>How it developed</h3><ol><li>Started with Python and basic HTTP concepts.</li><li>Built a FastAPI service for file operations and a dashboard.</li><li>Experimented with network storage using SFTP and SMB.</li><li>Added authentication and HTTPS in the local environment.</li></ol><h3>What I learned</h3><p>A working server needs more than application code. Permissions, networking, certificates and backups all matter.</p><h3>Try a beginner version</h3><p>Start with the Python lesson on this site, then run a simple local HTTP server. Keep it on your own machine while learning.</p><p><strong>Status:</strong> Working prototype; features and configuration continue to evolve.</p>`},
security:{label:'PROJECT / SECURITY',title:'Prime Security',body:`<p><strong>The idea:</strong> Turn system log events into information I can review and understand.</p><h3>How it developed</h3><ol><li>Observed SSH authentication events in a controlled environment.</li><li>Wrote a Python collector to identify relevant events.</li><li>Stored structured events in JSONL and SQLite.</li><li>Explored duplicate suppression and live monitoring.</li></ol><h3>What I learned</h3><p>Logs tell a story, but good monitoring requires context and careful interpretation.</p><h3>Try a beginner version</h3><p>Write a Python program that reads a sample log file and counts event types. Use synthetic log data, not private logs from other people.</p><p><strong>Status:</strong> In development.</p>`},
network:{label:'PROJECT / NETWORKING',title:'Network Lab',body:`<p><strong>The idea:</strong> Learn networking by experimenting with devices and local services I control.</p><h3>How it developed</h3><ol><li>Practiced Linux and Termux commands.</li><li>Learned about IP addresses, subnets and ports.</li><li>Hosted a local Python test server.</li><li>Observed how HTTP requests and network services behave.</li></ol><h3>What I learned</h3><p>Building a small lab makes abstract networking concepts visible. Practice only on systems you own or are explicitly authorized to test.</p><h3>Try a beginner version</h3><p>Run a local server on <code>127.0.0.1</code>, then open it in your own browser. Observe how a request becomes a response.</p><p><strong>Status:</strong> Ongoing learning laboratory.</p>`},
ai:{label:'PROJECT / AI',title:'AI Experiments',body:`<p><strong>The idea:</strong> Explore how personal assistants can interact with software while respecting permissions.</p><h3>How it developed</h3><ol><li>Built a Python command-based assistant.</li><li>Experimented with system status and opening applications.</li><li>Tested voice output and microphone input.</li><li>Explored permission-based tool design for future integrations.</li></ol><h3>What I learned</h3><p>Reliability, clear permissions and error handling are essential when software interacts with your system.</p><h3>Try a beginner version</h3><p>Make a command-line assistant that recognizes a few text commands and responds without needing internet access.</p><p><strong>Status:</strong> Experimental; not a finished assistant.</p>`}
};
const lessons={
linux:{label:'START HERE / LESSON 01',title:'Your first Linux commands',body:`<p><strong>Goal:</strong> Create a folder and a note using a terminal.</p><p>Open a Linux terminal or Termux. Run these commands one at a time:</p><pre><code>mkdir -p ~/my-first-lab\ncd ~/my-first-lab\nprintf 'Hello from my lab\\n' > hello.txt\ncat hello.txt</code></pre><p>You should see <code>Hello from my lab</code>. You created a directory, entered it, wrote a file and displayed its contents.</p><h3>Challenge</h3><p>Create a second text file in the same folder and display both files.</p>`},
python:{label:'START HERE / LESSON 02',title:'Your first Python script',body:`<p><strong>Goal:</strong> Create and run a simple Python program.</p><p>Install Python in your own development environment. Save the following in a file named <code>hello.py</code>:</p><pre><code>name = input("What's your name? ")\nprint(f"Welcome, {name}!")</code></pre><p>Run <code>python hello.py</code> (or <code>python3 hello.py</code> on systems that require it).</p><h3>Challenge</h3><p>Ask the user what subject they're learning and print an encouraging message using their answer.</p>`},
network:{label:'START HERE / LESSON 03',title:'Your first local web server',body:`<p><strong>Goal:</strong> Understand how a browser connects to a server running on your own computer.</p><p>After installing Python, open a terminal inside a folder containing a simple <code>index.html</code> file. Run:</p><pre><code>python -m http.server 8080 --bind 127.0.0.1</code></pre><p>Open <code>http://127.0.0.1:8080</code> on that same device. Your browser sends a request and Python returns the page.</p><h3>Challenge</h3><p>Edit the HTML file, refresh the browser and observe the change. This is a local learning exercise, not a production hosting setup.</p>`}
};
const dialog=document.getElementById('content-dialog');
function showContent(item){document.getElementById('dialog-label').textContent=item.label;document.getElementById('dialog-title').textContent=item.title;document.getElementById('dialog-body').innerHTML=item.body;dialog.showModal();}
if(dialog){
document.querySelectorAll('.detail-trigger').forEach(button=>button.addEventListener('click',()=>showContent(projects[button.dataset.project])));
document.querySelectorAll('.lesson-trigger').forEach(button=>button.addEventListener('click',()=>showContent(lessons[button.dataset.lesson])));
document.getElementById('dialog-close').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close();});
}
